name: workflow multijob
on:
  workflow_dispatch:  # Allows manual triggering of the workflow
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello, World!"
        
      - name: Print multiline message
        run: |
          echo "This is a multiline message."
          echo "It can span multiple lines."
          echo "Each line will be printed separately."
  job2:
    runs-on: ubuntu-latest
    needs: hello  # Ensures this job runs after the 'hello' job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello, World!"
        
      - name: Print multiline message
        run: |
          echo "This is a multiline message."
          echo "It can span multiple lines."
          echo "Each line will be printed separately."